import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'primereact/resources/themes/arya-green/theme.css';
import "./globals.css";
import BootstrapClient from "./libs/BootstrapClient";
import Header from "./components/Header";
import Footer from "./components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Crud Supabase",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
           <body className={`bg-dark text-white-50 ${inter.className}`}>
            <header>
              <Header/>
            </header>
            <main>
              {children}
            </main>
            <footer>
              <Footer/>
            </footer>
            
            </body>
           <BootstrapClient />
    </html>
  );
}
